export const IpcMainToRender = {
  appResume: "appResume",
  mainWindowStateChanged: "mainWindowStateChanged",
  triggerScreenshot: "triggerScreenshot",
  openConversationFromTray: "openConversationFromTray",
  shakeMainWindowEffect: "shakeMainWindowEffect",
};

export const IpcRenderToMain = {
  showMainWindow: "showMainWindow",
  clearSession: "clearSession",
  minimizeWindow: "minimizeWindow",
  maxmizeWindow: "maxmizeWindow",
  closeWindow: "closeWindow",
  showMessageBox: "showMessageBox",
  setKeyStore: "setKeyStore",
  getKeyStore: "getKeyStore",
  getKeyStoreSync: "getKeyStoreSync",
  updateScreenshotShortcut: "updateScreenshotShortcut",
  showInputContextMenu: "showInputContextMenu",
  getDataPath: "getDataPath",
  openFileDialog: "openFileDialog",
  chooseDownloadPath: "chooseDownloadPath",
  saveDownloadedFile: "saveDownloadedFile",
  downloadFileNative: "downloadFileNative",
  cancelDownloadFileNative: "cancelDownloadFileNative",
  openLocalPath: "openLocalPath",
  openLocalFolder: "openLocalFolder",
  uploadObjectFileFromPath: "uploadObjectFileFromPath",
  writeClipboardImage: "writeClipboardImage",
  writeClipboardImageFile: "writeClipboardImageFile",
  copyLocalFileToClipboard: "copyLocalFileToClipboard",
  startScreenshot: "startScreenshot",
  readClipboardImage: "readClipboardImage",
  saveScreenshotFile: "saveScreenshotFile",
  probeServerEnvironment: "probeServerEnvironment",
  probeImWsPort: "probeImWsPort",
  checkForUpdates: "checkForUpdates",
  notifyIncomingMessage: "notifyIncomingMessage",
  requestMainWindowAttention: "requestMainWindowAttention",
  trayConversationOpened: "trayConversationOpened",
  shakeMainWindow: "shakeMainWindow",
};
